# Numpy

The NumPy library is the core library for scientific computing in Python. It provides a high-preformance multidimensional array object, and tools for working with these arrays

##### Cielo Aholiva Higuera Gutiérrez

### *Creating Arrays*

#### Initial Placeholders

In [39]:
import numpy as np

In [208]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [187]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [191]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [11]:
np.zeros((3,4)) #Create an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((2,3,4), dtype = np.int16) #Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [13]:
d = np.arange(10,25,5) #Create an array of evenly
d

array([10, 15, 20])

In [14]:
np.linspace(0,2,9) #Create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [15]:
e = np.full((2,2),7) #Create a constant array
e

array([[7, 7],
       [7, 7]])

In [16]:
f = np.eye(2) #Create a 2x2 identity matrix
f

array([[1., 0.],
       [0., 1.]])

In [17]:
np.random.random((2,2)) #Create an array with random values

array([[0.6754188 , 0.04395544],
       [0.95445756, 0.2304558 ]])

In [18]:
np.empty((3,2)) #Create an empty array

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

### *I/O*

#### Saving and loading On Disk

In [21]:
np.save('my_array',a)

In [22]:
np.savez('array.npz', a, b)

#### Saving and loading Text Files

In [24]:
np.loadtxt("myfile.txt")

array([1., 2.])

In [25]:
np.genfromtxt("my_file.cvs", delimiter= ',')

array(nan)

In [26]:
np.savetxt("myarray.txt", a, delimiter=" ")

#### Inspecting Your Array

In [28]:
a.shape #Array dimensions

(3,)

In [29]:
len(a) #Length of array

3

In [30]:
b.ndim #Number of array dimensions

2

In [31]:
e.size #Number of array elements

4

In [32]:
b.dtype #Data type of array elements

dtype('float64')

In [33]:
b.dtype.name #Name of data type

'float64'

In [34]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

#### Data Types

In [36]:
np.int64 #Signed 64 bit integer types

numpy.int64

In [43]:
np.float32 #Standard double-precision floating point

numpy.float32

In [57]:
np.complex128 #Complex numbers represented by 128 floats

numpy.complex128

In [65]:
np.bool_ #Boolean type storing TRUE and FALSE values

numpy.bool_

In [75]:
np.dtype(object) #Python object type

dtype('O')

In [77]:
np.string_ #Fixed-length string type

numpy.bytes_

In [79]:
np.unicode_ #Fixed-length string type

numpy.str_

#### Array Mathematics

In [90]:
g = a - b #Subtraction
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [92]:
np.subtract(a,b) #Subtraction

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [94]:
b + a #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [96]:
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [98]:
a/b #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [100]:
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [102]:
a*b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [104]:
np.multiply(a,b) #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [106]:
np.exp(b) #Exponentiation

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [114]:
np.sqrt(b) #Square root

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [116]:
np.sin(a) #Print sines of an array

array([0.84147098, 0.90929743, 0.14112001])

In [118]:
np.cos(b) #Element-wise cosine

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [122]:
np.log(a) #Element-wise natural logarithm

array([0.        , 0.69314718, 1.09861229])

In [124]:
e.dot(f) #Dot product

array([[7., 7.],
       [7., 7.]])

#### Comparision

In [131]:
a == b #Element-wise comparision

array([[ True,  True,  True],
       [ True,  True,  True]])

In [133]:
a<2 #Element-wise comparision

array([[ True, False, False],
       [False, False, False]])

In [135]:
np.array_equal(a,b) #Array-wise comparasion

True

#### Aggregate Functions

In [140]:
a.sum() #Array-wise sum

21.5

In [142]:
a.min() #Array-wise minium value

1.5

In [144]:
b.max(axis=0) #Maximum value of an array row

array([4., 5., 6.])

In [146]:
b.cumsum(axis=1) #Cumulative sum of the elements

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [148]:
a.mean() #Mean

3.5833333333333335

In [150]:
np.median(b) #Median

3.5

In [152]:
np.corrcoef(a) #Correlation coefficient

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])

In [154]:
np.std (b) #Standard deviation

1.5920810978785667

### *Copying Arrays*

In [279]:
h = a.view() #Create a view of the array with the same data
h

array([1, 2, 3])

In [163]:
np.copy(a) #Create a copy of the array

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [281]:
h = a.copy() #Create a deep copy of the array
h

array([1, 2, 3])

### *Sorting Arrays*

In [181]:
a.sort() #Sort an array

In [197]:
c.sort(axis=0) #Sort the elements of an arrays's axis

### *Subsetting, Slicing, Indexing*

#### Subsetting

In [210]:
a[2] #Select the element at the 2nd index

3

In [212]:
b[1,2] #Select the element at row column 2 (equivalent to b[1][2])

6.0

#### Slicing

In [217]:
a[0:2] #Select items at index 0 and 1

array([1, 2])

In [219]:
b[0:2,1] #Select items at rows 0 and  in the column 1

array([2., 5.])

In [221]:
b[:1] #Select all items at rows 0 and 1 in column 1

array([[1.5, 2. , 3. ]])

In [223]:
c[1,...] #Same as [1,:,:]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [225]:
a[ : :-1] #Reversed array a array ([3, 2, 1])

array([3, 2, 1])

#### Boolean Indexing

In [232]:
a[a<2] #Select elements from a less than 2

array([1])

#### Fancy Indexing

In [235]:
b[[1, 0, 1, 0], [0, 1, 2, 0]] #Select elements (1,0), (0,1), (1,2) and (0,0)

array([4. , 2. , 6. , 1.5])

In [239]:
b[[1, 0, 1, 0]][:,[0,1,2,0]] #Select a subset of the matrix's rows and columns

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

### *Array Manipulation*

#### Transposing Array

In [249]:
i = np.transpose(b) #Permute array dimensions
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [251]:
i.T #Permute array dimensions

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

#### Chaging Array Shape

In [257]:
b.ravel() #Flatten the array

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [259]:
g.reshape(3,-2) #Reshape, but don't change data

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

#### Adding/Removing Elements

In [305]:
np.resize(h,(2,6)) #Return a new array with shape (2,6)

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [307]:
np.append(h,g) #Append items to an array

array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [309]:
np.insert(a, 1, 5) #Insert items in an array

array([1, 5, 2, 3])

In [313]:
np.delete(a,[1]) #Delate items from an array

array([1, 3])

#### Combining Arrays

In [318]:
np.concatenate((a,d),axis=0) #Concatenate arrays

array([ 1,  2,  3, 10, 15, 20])

In [320]:
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [322]:
np.r_[e,f] #Stack arrays vertically (row-wise)

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [324]:
np.hstack((e,f)) #Stack arrays horizontally (dcolumn-wise)

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [326]:
np.column_stack((a,d)) #Create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [ ]:
np.c_[a,d] #Create stacked column-wise arrays

#### Splitting Arrays

In [330]:
np.hsplit(a,3) #Split the array horizontally at the 3rd index 

[array([1]), array([2]), array([3])]

In [332]:
np.vsplit(c,2) #Split the array vertically at the 2nd index

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 3.],
         [4., 5., 6.]]])]